export const GET_CHARACTERS = "GET_CHARACTERS"
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR"

export const GET_COMICS = "GET_COMICS"
export const GET_COMICS_ERROR = "GET_COMICS_ERROR"

export const GET_CHARACTER_DETAILS = "GET_CHARACTER_DETAILS"
export const GET_CHARACTER_DETAILS_ERROR = "GET_CHARACTER_DETAILS_ERROR"

export const GET_COMICS_DETAILS = "GET_COMICS_DETAILS"
export const GET_COMICS_DETAILS_ERROR = "GET_COMICS_DETAILS_ERROR"
